import React from 'react'

const About = () => {
  return (
    <>
    <article className='about'>
      <h1>Cookpal</h1>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate ab impedit, perspiciatis debitis dolores, temporibus at rem, fugit quo doloremque eligendi dolorem maiores repellat ut quaerat eos voluptatibus nisi commodi accusamus laboriosam nostrum voluptatum? Sequi illo voluptatibus perferendis a est quia, eos hic praesentium, dolorem alias consectetur cum iure odio sapiente. Quam amet magnam eum reiciendis sint repudiandae incidunt minima earum quas? Sed quae, distinctio nulla doloremque est vel quia vitae iste illo. Adipisci possimus, corporis reiciendis officiis beatae velit est. Quis dolor voluptatibus officia incidunt. Beatae quod sapiente, nostrum expedita repellat officia temporibus magni sit consequuntur aspernatur repellendus a. Velit nulla ipsa, voluptas facere quibusdam corporis iste doloribus quisquam reprehenderit quidem. Voluptatem, distinctio. Nesciunt ipsam debitis ut nulla dolorum ipsa dolores nam, est veritatis dolorem accusamus repellendus fuga officia, explicabo fugit in illo iure. Magni nostrum atque officiis voluptatibus iure sapiente animi deleniti inventore esse distinctio expedita minus iste, quibusdam consectetur doloribus fugit voluptas maiores ullam perspiciatis ea natus! Quasi provident eum fuga eligendi, nemo repellat iusto fugiat qui ipsa atque est. Temporibus corrupti ducimus tempora, quia possimus in sit ab ratione obcaecati voluptatum tempore vel a nemo ipsa sequi labore? Omnis sit libero unde sint eveniet est dolorem praesentium consequuntur explicabo mollitia aliquid eligendi labore, magnam optio ex ipsam ratione ad ea veritatis. A voluptatem animi soluta! Voluptatum nulla adipisci iusto temporibus laborum voluptas illum aliquam illo amet voluptatem atque numquam minima, modi ea quidem ullam. Eius ab accusamus necessitatibus iste reiciendis qui, cum debitis, minus numquam repellendus exercitationem voluptate culpa dolorem quae. Enim molestias dolor fugiat placeat suscipit architecto incidunt eius dicta sequi commodi, asperiores 
        beatae repudiandae quod nisi animi obcaecati voluptatum provident blanditiis corrupti eveniet consequuntur modi. Impedit facere voluptate architecto placeat maiores velit perferendis explicabo porro, dignissimos, harum voluptatum dolores! Ab voluptatibus enim praesentium omnis.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis unde cum, laboriosam ipsam obcaecati officiis consectetur, maiores id animi dolorem harum sed dignissimos labore hic temporibus assumenda aliquam, quam soluta. Voluptatem perferendis architecto esse quos enim vero quia, aperiam veritatis facilis, suscipit sit voluptates maxime eveniet dolorum sequi laboriosam praesentium doloremque alias excepturi aliquid maiores mollitia exercitationem hic soluta! Eius velit a ut dignissimos deserunt minima alias sint facere nisi reiciendis quis voluptates ducimus enim eligendi, repudiandae quae optio quasi? Nemo excepturi neque esse quos cum consequatur voluptate eveniet nisi consequuntur, quas aliquid placeat molestiae, possimus sapiente recusandae veniam delectus impedit, cupiditate dolore a! Earum delectus deleniti rem dolore eligendi quae nihil! Magni, itaque a! Assumenda eum qui accusamus saepe esse aliquid inventore sapiente nihil explicabo? Est commodi maiores, maxime iure consectetur perspiciatis rerum facilis, cumque, eos numquam architecto quia quisquam sequi quod modi fuga ea et ipsa animi itaque? Reprehenderit at laboriosam inventore molestias in ex accusamus, eos sed explicabo dolorem, ipsam nemo omnis quibusdam! Libero laborum sunt voluptatum voluptate dicta earum tempora debitis. Iure nobis et iusto laudantium ea repudiandae debitis eligendi ullam ut nesciunt voluptas rerum amet enim veritatis eaque perspiciatis libero temporibus aperiam voluptate vero illum fugiat, laborum aliquid possimus. A nam corporis 
        odit quia cumque asperiores veniam aspernatur laboriosam, nisi maxime in inventore dolor est sunt.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus harum ipsum officia! Dolore, maxime deserunt eius architecto, officiis repudiandae error id odio beatae cupiditate fugiat necessitatibus commodi tempore natus quam.</p>
    
    </article>
    </>
  )
}

export default About